#!/usr/bin/env Rscript
#' ---
#' title: bkcd - bkcd.R - xkcd like plots using base graphicsfunctions and operators
#' author: Detlef Groth, University of Potsdam
#' date: 2022-01-26
#' ---
#' 
#' ## NAME
#' <a name="home"> </a>
#' 
#' _bkcd.R_ - R environment and standalone application to create xkcd like plots using the R graphics library.
#' 
#' ## TABLE OF CONTENTS
#' 
#' * [SYNOPSIS](#synopsis)
#' * [DESCRIPTION](#description)
#' * [USAGE](#usage)
#' * [FUNCTIONS](#functions)
#'     * [bkcd$axes](#axes) - creates xkcd compatible axes
#'     * [bkcd$emptyplot](#emptyplot) - creates an empty plot surface
#'     * [bkcd$points](#points) - add polygon or line based plotting characters to an existing plot
#'     * [bkcd$tikz2xkcd](#tikz2xkcd) - convert TikZ files to xkcd compatible TikZ files with decorations
#'     * [pkcd$xyplot](#xyplot) - xkcd compatible plotting of two numerical vectors
#' * [EXAMPLES](#examples)
#' * [CITATION](#citation)
#' * [DOCUMENTATION](#documentation)
#' * [LINKS](#links)
#' * [TODOS](#todos)
#' * [CHANGELOG](#changelog)
#' * [LICENSE / AUTHOR](#license)
#' 
#' ## SYNOPSIS
#' <a name="synopsis"> </a> 
#' 
#' Sourcing:
#' 
#' ``` 
#' source("~/R/dlib/bkcd.R")
#' library(tikzDevice)
#' tikz("file.tex",sanitize=TRUE)
#' barplot(1:4,names.arg=LETTERS[1:4],col=2:5,axes=FALSE,
#'         main="barplot",ylim=c(0,4.5))
#' bkcd$axes(2)
#' dev.off()
#' bkcd$tikz2xkcd("file.tex","file.pdf",fontname="Humor Sans")
#' ```
#' 
#' Standalone application:
#' 
#' ```
#' Rscript ~/R/dlib/bkcd.R --help   
#' Rscript ~/R/dlib/bkcd.R --convert file.tex file.png
#' Rscript ~/R/dlib/bkcd.R --test # should create the barplot above
#' ```
#' 
#' ## DESCRIPTION
#' 
#' The file _bkcd.R_ contains the code for an R environment _bkcd_ to create xkcd like plots using the
#' base graphics package of R. The file _bkcd.R_ can be sourced into your own R code
#' or it can be used as a standalone application to convert existing TikZ figures created with base graphics
#' methods into other TikZ-TeX filesand futher converted directly into PDF files (Using the xelatex compiler) and thereafter as well
#' into PNG files (using the ghostscript interpreter). 
#' The R script is based on the TikZ graphicsdevice and an installed comic font like
#' [Humor Sans](https://github.com/shreyankg/xkcd-desktop),
#' [Fuzzy Bubbles](https://fonts.google.com/specimen/Fuzzy+Bubbles)
#' or the [xkcd Script font]((https://github.com/ipython/xkcd-font/tree/master/xkcd-script/font).
#' 
#' __Attention:__ Please note, that the image generation via the pipeline R-latex-ghostscript is much slower than native image generation within R. 
#' For instance this complete document took almost 3 minutes to compile on my Linux Machine (4 CPU's 2.1Ghz, 16GB RAM).
#' In case of using it within a R-Markdown document, like this one, use the
#' code chunk option `cache=TRUE` if appropriate, this way the compile time for this document
#' was reduced to 0.51 seconds!! if the code in the code chunks did not change and
#' just modifications in the documentation text were done. 
#' Furthermore do not expect that all bells and whistles of R plots will
#' work as expected. Use this code carefully, for instance as an opener slide in a presentation or to demonstrate ideas or to do less
#' serious things, the plots might generated by this script are less useful to analyze real data.
#' 
#' Requirements:
#' 
#' * R with package *tikzDevice*
#' * LaTeX with *xelatex* and packages *standalone*, *tikz*, *pgf*, PDF output
#' * Optional: Ghostscript for PNG conversion, you could choose any other converter by yourself from the PDF file produced by *xelatex*
#' * Optional: [pdf2svg](https://github.com/dawbarton/pdf2svg) for SVG generation (optional), again you could choose any other converter by yourself from the PDF file produced by *xelatex*
#' 
#' Public Functions:
#'
#'   * [bkcd$axes](#axes) - creates xkcd compatible axes
#'   * [bkcd$emptyplot](#emptyplot) - creates an empty plot surface
#'   * [bkcd$points](#points) - add polygon or line based plotting characters to an existing plot
#'   * [bkcd$tikz2xkcd](#tikz2xkcd) - convert TikZ files to xkcd compatible TikZ files with decorations
#'   * [pkcd$xyplot](#xyplot) - xkcd compatible plotting of two numerical vectors
#' 
#' ## USAGE
#' <a name="usage"> </a>
#' 
#' ### Source bkcd.R
#' 
#' To use the functions in your own R programs and analysis just source the file `bkcd.R` into your R application. It is recommended to place the file into the R folder in your HOME directory.
#'
#' ```{r label=source}
#' source("bkcd.R")
#' ```
#' 
#' All function of this file are added to an environment variable called _bkcd_. 
#' To have a look which variables and functions exists in this namesspace you can use the function call
#' `ls(bkcd)`. Here is the output:
#' 
#' ```{r label=ls}
#' ls(bkcd)
#' ```
#' 
#' Public methods names start with a lowercase letter. You should only use them in your R scripts.
#' 
#' ```{r label=ls2}
#' ls(bkcd,pattern="^[a-z]")
#' ```
#' 
#' ### Application bkcd.R
#' 
#' Alternatively, if you make the script executable and you 
#' move into a folder belonging to your PATH variable,
#' you can use the script `bkcd.R` as a standalone executable to convert TikZ figure files into xkcd-tex files and optional process them further to PNG and PDF files like this:
#' 
#' ```
#' $ bkcd.R --convert infile.tex infile.png
#' ```
#' 
#' Possible output file formats are :
#' 
#' * `.tex` - standalone texfile with embedded LaTeX commands for xkcd style (not all TikZ figure files from non-R-tikzDevice generated ones will work!)
#' * `.pdf` - tex document with xkcd style macros is further processed to a pdf file using `xelatex`
#' * `.png` - tex document with xkcd style macros is processed to pdf (xelatex), then to png using ghostscript
#' 
#' For a pipeline overview see the [flowchart](#flowchart) below. For svg output
#' I recommend using the command line tool [pdf2svg](https://github.com/dawbarton/pdf2svg) on the pdf output file.
#' 
library(tikzDevice)
bkcd = new.env()
bkcd$VERSION = "2022.01.30"
.calls=sys.calls()
srx=grep("^source",.calls)
idx=srx[length(srx)]
bkcd$FILENAME = gsub("source\\(.(.+).\\)","\\1",.calls[idx])
rm(.calls,srx,idx)

#' ## FUNCTIONS
#' <a name="functions"> </a>
#'
#' <a name="axes"> </a>
#' 
#' **bkcd$axes(which=c(1,2))** 
#' 
#' > Creates xkcd compatible axes.
#' 
#' > This function creates axes which are compatible for the xkcd display. 
#'   In standard axes plotting we have acutally two lines which are exactly on the same line, the box-line and the axis line.
#'   During the sketching then the two lines diverge slightly which might be a little bit disturbuing.
#'   Below in the example section you can compare the two versions.
#' 
#' > Arguments:
#' 
#' > - _which_ - vector with numbers from 1 to 4 for the axis, default: c(1,2)
#'
#' > Examples:
#' 
#' > Below two examples, left the traditional approach to create
#'   boxed histograms and xy-plots. Right the fix using the `bkcd$axes` function. In the left plots, there is a visible double line on the x- and on the y-axis.
#' 
#' > ```{r label=axes,fig=FALSE,results="hide",cache=TRUE}
#' library(tikzDevice)
#' # sanitize=TRUE to avoid interpretation of special symbols 
#' # like the Dollar symbol as LaTeX symbols
#' tikz("tikz-axes.tex",sanitize=TRUE,width=9,height=6)
#' data(iris)
#' par(mfcol=c(2,2),mai=rep(0.6,4))
#' # standard approach
#' hist(iris$Sepal.Length)
#' box()
#' plot(iris$Sepal.Length~iris$Sepal.Width,
#'    col=as.numeric(iris$Species)+1,pch="+",cex=2)
#' # using bkcd$axes avoids line overlays
#' hist(iris$Sepal.Length,axes=FALSE)
#' bkcd$axes()
#' plot(iris$Sepal.Length~iris$Sepal.Width,axes=FALSE,
#'    col=as.numeric(iris$Species)+1,pch="+",cex=2)
#' bkcd$axes()
#' dev.off()
#' bkcd$tikz2xkcd("tikz-axes.tex","tikz-axes.png",fontname="Humor Sans")
#' > ```
#'
#' <center>
#' ![](tikz-axes.png){#id width=800px} 
#' 
#' **Figure: 1**: Effect of double lines on x and y-axis. 
#' </center>
#' 

bkcd$axes = function (which=c(1,2)) {
    for (i in which) {
        axis(i,lwd=0,lwd.ticks=1) 
    }
    box()
}

#' <a name="emptyplot"> </a>
#' **bkcd$emptyplot(...)** 
#' 
#' > Creates an empty plot surface.
#' 
#' > This function creates an empty plot surface which can be used as a starter
#'   to build your own plot or figures later in a stepwise manner.
#' 
#' > Arguments:
#' 
#' > - _xlim_ - the (hidden) limits of the x-axis, default: c(-0.05,1.05)
#'   - _ylim_ - the (hidden) limits of the y-axis, default: c(0,0)
#'
#' > Examples:
#' 
#' > Let's rebuild the famous ["The Data So Far"](https://xkcd.com/373/) comic:
#' 
#' > ```{r label=emptyplot,fig=FALSE,results="hide",cache=TRUE}
#' library(tikzDevice)
#' tikz("tikz-power.tex")
#' bkcd$emptyplot()
#' lines(x=c(0,1),y=c(0.02,0.02),lwd=4) # xaxis
#' lines(x=c(0,0),y=c(0.02,0.95),lwd=4) # yaxis
#' rect(0.56,0.03,0.76,0.9,col=4,border=4) # box
#' lines(x=c(0.66,0.66),y=c(-0.01,0.03),lwd=2) # tick1
#' lines(x=c(0.25,0.25),y=c(-0.01,0.03),lwd=2) # tick2
#' axis(1,lwd=0,c("Confirmed\n by Experiment",
#'   "Refuted By\nExperiment"),at=c(0.25,0.66),
#'   cex.axis=1.6) # labels
#' mtext(side=3,"    Claims of Supernatural Powers",cex=1.8)
#' dev.off()
#' bkcd$tikz2xkcd("tikz-power.tex","tikz-power.png",fontname="Humor Sans")
#' > ```

#' 
#' ![](tikz-power.png){#id width=400px class=center} 
#' 
#' <div class="center">
#' **Figure 2**: Claims of Supernatural Powers (emptyplot-demo).
#' </div>
#'
#' 

bkcd$emptyplot = function (xlim=c(-0.05,1.05),ylim=c(0,1)) {
    plot(0.5,type="n",xlim=xlim,ylim=ylim,xlab="",ylab="",axes=FALSE)
}

#' <a name="points"> </a>
#' **bkcd$points(x,y,...)** 
#' 
#' > Add polygon based plotting characters to an existing plot.
#' 
#' > This function adds polygon based plotting characters to an existing plot.
#'   Using a polygon ensures that the plotting characters are made more sketchy
#'   using the tikz/pgf LaTeX document with the xkcd style.
#' 
#' > Arguments:
#' 
#' > - _x_ - vector of x coordinates
#'   - _y_ - vector of y coordinates
#'   - _pch_ - type of polygon, can be either 'circ', 'rect', 'dia', 'tri' or 'star', default: 'circ'
#'   - _col_ - color, default: 2 (red)
#'   - _fill_ - should the polygon be filled, default: TRUE
#'   - _cex_ - character expansion, default: 1
#'
#' > See also:
#' 
#' > * [bkcd$xyplot](#xyplot)
#'
#' > Examples:
#' 
#' > ```{r label=points,fig=FALSE,results="hide",cache=TRUE}
#'  library(tikzDevice)
#'  tikz('tikz-plotpoints.tex', width = 8, height = 4.5)
#'  data(iris)
#'  bkcd$xyplot(iris$Sepal.Length,iris$Sepal.Width,
#'     col=as.numeric(iris$Species)+1,
#'     pch="dia",xlim=c(4,8),main="xyplot(diamond)",
#'     fill=FALSE)
#'  bkcd$points(x=rep(6.5,3),y=c(4.2,4.5,4.8),pch="dia",
#'     col=2:4,cex=1)
#'  text(x=rep(6.6,3),y=c(4.2,4.5,4.8),
#'     labels=c('setosa','versicolor','virginica'),pos=4)
#'  dev.off()
#'  bkcd$tikz2xkcd("tikz-plotpoints.tex","tikz-plotpoints.png",fontname="Fuzzy Bubbles")
#' > ```
#'
#' <div class="center">
#' ![](tikz-plotpoints.png)
#' 
#' **Figure 3**: Iris data plot (points-demo).
#' </div>
#' 

bkcd$points = function (x=0,y=0,pch="circ",col=2,fill=TRUE,cex=1) {
    ellipse <- function(x,y,rho=0, length = 99,
                        scale=1,
                        height=1,
                        width=1) {
        k <- seq(0, 2 * pi, length = length)
        xa <- cos(k + acos(rho)/2)/(3/scale+0.1)
        ya <- cos(k - acos(rho)/2)/(3/scale+0.1)
        ya=ya*height    
        xa=xa*width
        return(list(x=x+xa*-1,y=y+ya))
    }
    rectangle <- function (x=0,y=0,height=1,width=1) {
        xa=c(-0.5,0.5,0.5,-0.5)*width
        ya=c(-0.5,-0.5,0.5,0.5)*height
        return(list(x=xa,y=ya))
    }
    diamond <- function (x=0,y=0,height=1,width=1) {
        xa=c(-0.5,0,0.5,0)*width
        ya=c( 0  ,-0.5,0 ,0.5)*height
        return(list(x=xa,y=ya))
    }
    triangle <- function (x=0,y=0,height=1,width=1) {
        xa=c(-0.5,0.5,0)*width
        ya=c(-0.5,-0.5,0.5)*height
        return(list(x=xa,y=ya))
    }
    star <- function (x=0,y=0,height=1,width=1) {
        xi=c(0.0000,-0.0625,-0.2500,-0.1250,-0.1875,0.0000,0.1875,0.1250,0.2500,0.0625)
        yi=c(0.2750,0.0250,0.0250,-0.1000,-0.2875,-0.1625,-0.2875,-0.1000,0.0250,0.0250)
        xs=xi/(max(xi)-min(xi))
        ys=yi/(max(yi)-min(yi))
        return(list(x=xs,y=ys))
    }
    if (length(col)==1) {
        col=rep(col,length(x))
    }
    circ=ellipse(0,0,length=20)
    rec=rectangle(0,0)
    tri=triangle(0,0)
    dia=diamond(0,0)
    star=star(0,0)    
    p.usr=par("usr")
    xdim=p.usr[2]-p.usr[1]
    ydim=p.usr[4]-p.usr[3]
    circ$x=circ$x/25*xdim*cex
    circ$y=circ$y/25*ydim*cex
    rec$x=rec$x/30*xdim*cex
    rec$y=rec$y/30*ydim*cex
    tri$x=tri$x/25*xdim*cex
    tri$y=tri$y/25*ydim*cex
    dia$x=dia$x/25*xdim*cex
    dia$y=dia$y/25*ydim*cex
    star$x=star$x/25*xdim*cex
    star$y=star$y/25*ydim*cex
    pchs=list(dia=dia,circ=circ,rect=rec,tri=tri,star=star)
    for (i in 1:length(x)) {
        if (length(pch) ==1) {
            pchar=pchs[[pch]]
        } else {
            pchar=pchs[[pch[i]]]
        }
        if (fill) {
            polygon(pchar$x+x[i],pchar$y+y[i],border=col[i],col=col[i])
        } else {
            polygon(pchar$x+x[i],pchar$y+y[i],border=col[i],lwd=2)
        }
    }
}

#' <a name="xyplot"> </a>
#' **bkcd$xyplot(x,y,...)** 
#' 
#' > Xkcd styled plotting of two numerical vectors.
#' 
#' > This function ensures the right placement of the axes for the xyplot uses
#'   polygon based plotting characters to ensure the sketch effect.
#' 
#' > Arguments:
#' 
#' > - _x_ - vector of x coordinates
#'   - _y_ - vector of y coordinates
#'   - _pch_ - type of polygon, can be either 'circ', 'rect', 'dia', 'tri' or 'star', default: 'circ'
#'   - _col_ - color, default: 2 (red)
#'   - _fill_ - should the polygon be filled, default: TRUE
#'   - _cex_ - character expansion, default: 1
#'   - _axes_ - should the axes be plotted, default: TRUE
#'   - _grid_ - should the internal grid be plotted, default: TRUE
#'   - _asp_ -  aspect ratio, default: 1 
#'   - _pty_ - pty paramater to keep ratio of plot width and height 's' - is same/square, 'm' is maximal area, default: 's'
#'   - _..._ - remaining arguments are forwarded to the standard plot function
#'
#' > See also:
#' 
#' > - [bkcd$points](#points)
#' 
#' > Examples:
#' 
#' > ```{r label=xyplot,fig=FALSE,results="hide",cache=TRUE}
#'  library(tikzDevice)
#'  tikz('tikz-xyplot.tex', width = 9, height = 4.5)
#'  par(mfrow=c(1,2),mai=c(0.6,0.6,0.8,0.2))
#'  data(iris)
#'  bkcd$xyplot(iris$Sepal.Length,iris$Sepal.Width,
#'     col=as.numeric(iris$Species)+1,
#'     pch="star",main="xyplot(star)")
#'  bkcd$xyplot(iris$Sepal.Length,iris$Sepal.Width,
#'     col=as.numeric(iris$Species)+1,
#'     pch="circ",main="xyplot(circle)")
#'  dev.off()
#'  bkcd$tikz2xkcd("tikz-xyplot.tex","tikz-xyplot.png",fontname="Fuzzy Bubbles")
#' > ```
#'
#' <div class="center">
#' ![](tikz-xyplot.png)
#'
#' **Figure 4**: xy-plot for iris data (xyplot-demo).
#' </div>
#' 

bkcd$xyplot = function (x=0,y=0,pch="circ",col=2,
                        fill=TRUE,cex=1,axes=TRUE,grid=TRUE,
                        asp=1,pty="s",...) {
    opar=par(pty=pty)
    plot(x,y,type="n",axes=FALSE,asp=asp,...)
    if (grid) {
        grid()
    }
    if (axes) {
        axis(1,lwd=0,lwd.ticks=1) 
        axis(2,lwd=0,lwd.ticks=1) 
        box()
    }
    bkcd$points(x,y,pch=pch,col=col,fill=fill,cex=cex);
    par(opar)
}

#' <a name="tikz2xkcd"> </a>
#' **bkcd$tikz2xkcd(x,y,...)** 
#' 
#' > Convert TikZ files to xkcd compatible tikz files with decorations.
#' 
#' > This function is the actual main converting function. 
#'   It converts a standard TeX-TikZ file (created with the *tikzDevide* package), to a TikZ file with xkcd sytling LaTeX macros and
#'   thereafter compiles the latter to a PDF file using the *xelatex* executable. 
#'   In case that the file extension of the requested output file is PNG, the PDF file is further
#'   converted to a PNG using the Ghostscript interpreter.
#' 
#' > Arguments:
#' 
#' > - _infile_ - TikZ LaTeX input file created with the the *tikz* command from the *tikzDevice* package
#'   - _outfile_ - a LaTeX or PNG or a PDF output file
#'   - _standalone_ - should the generated file be a standalone LaTeX files which can be compiled directly using the xelatex application, in case of PNG and PDF output this is automatically standalone=TRUE, default: FALSE
#'   - _fontname_ - the font which should be used, should be an installed OTF or TTF file in comic style
#'   - _include_ - which additional tex files should be included, default: NULL
#'   - _fontsize_ - which LaTeX fontsize, default: "large"
#'   - _resolution_ - resolution in DPI for PNG output, default: 144
#'
#' > Examples:
#' 
#' > ```{r label=tikz2xkcd,fig=FALSE,results="hide",cache=TRUE}
#' tikz('tikz-pie.tex', width = 4.5, height = 4.5)
#' par(mai=rep(0.8,4))
#' pie(table(iris$Species)*c(0.9,0.6,0.8), 
#'   col=2:4,main="pie-chart")
#' dev.off()
#' bkcd$tikz2xkcd("tikz-pie.tex","tikz-pie.png",fontname="Fuzzy Bubbles")
#' tikz('tikz-barplot.tex')
#' barplot(table(iris$Species)*c(0.9,0.6,0.8),ylim=c(0,55), 
#'         col=2:4,main="bar-plot",xlab="Species",axes=FALSE,cex.main=1.4)
#' axis(2,lwd=0,lwd.ticks=1) 
#' box()
#' dev.off()
#' bkcd$tikz2xkcd("tikz-barplot.tex","tikz-barplot.png",fontname="Fuzzy Bubbles")
#' > ```
#' 
#' ![](tikz-pie.png){#id width=400px} ![](tikz-barplot.png){#id width=400px} 
#'
#' <div class="center">
#' **Figure 5**: pie and barplot demos (tikz2xkcd-demo).
#' </div>
#' 

bkcd$tikz2xkcd = function (infile,outfile, standalone=FALSE,
                      fontname="xkcd Script",
                      include=NULL,fontsize="large",
                      resolution=144) {
    header="
\\documentclass[preview]{standalone}
\\usepackage{fontspec}
\\setmainfont{__FONTNAME__}
\\usepackage{tikz}
\\usetikzlibrary{calc,decorations,patterns,arrows,decorations.pathmorphing}
\\definecolor{pltblue}{HTML}{1F77B4}

\\makeatletter
\\pgfset{
  /pgf/decoration/randomness/.initial=2,
  /pgf/decoration/wavelength/.initial=100
}
\\pgfdeclaredecoration{sketch}{init}{
  \\state{init}[width=0pt,next state=draw,persistent precomputation={
    \\pgfmathsetmacro\\pgf@lib@dec@sketch@t0
  }]{}
  \\state{draw}[width=\\pgfdecorationsegmentlength,
  auto corner on length=\\pgfdecorationsegmentlength,
  persistent precomputation={
    \\pgfmathsetmacro\\pgf@lib@dec@sketch@t{mod(\\pgf@lib@dec@sketch@t+pow(\\pgfkeysvalueof{/pgf/decoration/randomness},rand),\\pgfkeysvalueof{/pgf/decoration/wavelength})}
  }]{
    \\pgfmathparse{sin(2*\\pgf@lib@dec@sketch@t*pi/\\pgfkeysvalueof{/pgf/decoration/wavelength} r)}
    \\pgfpathlineto{\\pgfqpoint{\\pgfdecorationsegmentlength}{\\pgfmathresult\\pgfdecorationsegmentamplitude}}
  }
  \\state{final}{}
}
\\tikzset{xkcd/.style={decorate,decoration={sketch,segment length=0.5pt,amplitude=0.5pt}}}
\\makeatother

\\pgfmathsetseed{1}

\\pagestyle{empty}
"    
    texfile=outfile
    #if (file.exists(outfile) & file.mtime(infile)>file.mtime(outfile)) {
    #    # if after pdf creation a png is requested the run is useless
    #    return()
    #}
    pdffile=""
    pngfile=""
    # TODO - Windows / Non-Bash checks
    if (grepl("[pP][dD][fF]$",texfile)) {
        standalone=TRUE
        sys=system("command -v xelatex",intern=TRUE)
        if (sys == "") {
            stop("xelatex required")
        }
        pdffile=texfile
        texfile=gsub(".[pP][dD][fF]$","-out.tex",texfile)
    }
    if (grepl("[pP][nN][gG]$",texfile)) {
        standalone=TRUE
        sys=system("command -v gs",intern=TRUE)
        if (sys == "") {
            stop("gs (Ghostscript) required")
        }
        sys=system("command -v xelatex",intern=TRUE)
        if (sys == "") {
            stop("xelatex required")
        }
        pngfile=texfile
        texfile=gsub(".[pP][nN][gG]$","-out.tex",texfile)
    }
    fout = file(texfile,"w")
    fin  = file(infile, "r")
    header=gsub("__FONTNAME__",fontname,header)
    if (standalone) {
        cat(header,"\n",sep="",file=fout)
    }
    if (!is.null(include)) {
        cat("\\include{header}\n",sep="",file=fout)
    }
    if (standalone) {
        cat("\\begin{document}","\n",sep="",file=fout)
    }
    cat("\\",fontsize,"\n",sep="",file=fout)
    while(length((line = readLines(fin,n=1)))>0) {
        line=gsub("\\path\\[draw","\\path\\[xkcd,draw",line)
        line=gsub("\\path\\[fill","\\path\\[xkcd,fill",line)        
        cat(line,"\n",sep="",file=fout)
    }
    
    if (standalone) {
        cat("\\end{document}\n",file=fout)
    }
    close(fout)
    close(fin)
    res=""
    if (pdffile != "" | pngfile != "") {
        cat("\n running xelatex - if this does not finish, press X and ENTER ...")
        res=system(sprintf("xelatex %s 2>&1",texfile),intern=TRUE)
    }
    if (pngfile != "") {
        pdffile=gsub(".tex$",".pdf",texfile)
        res=system(sprintf("gs -dBATCH -dNOPAUSE -dQUIET -sDEVICE=pngalpha -sOutputFile=%s -r%i %s",pngfile,resolution,pdffile),intern=TRUE)
    }
    invisible(res)
}

# private methods (starts with uppercase letter)

bkcd$Usage = function () {
    cat("XKCD like plots for the R graphics package\n\n")
    cat("Usage:\n\n  Rscript bkcd.R --docu\n      compile documentation bkcd.html\n\n")
    cat("  Rscript bkcd.R --convert infile.tex outfile.png\n      convert tikz files into xkcd-tex, png or pdf files\n\n")
    cat("  Rscript bkcd.R --help funcname\n      display help about the given function\n") 
    cat("  Rscript bkcd.R --test\n     needs Humor-Sans.ttf font installed\n")
    cat("\n")
    q()
}

#'
#' ## EXAMPLES
#' <a name="examples"> </a>
#' 
#' Below a few more examples. Let's start with a boxplot:
#' 
#' ```{r label=boxplot,results="hide",cache=TRUE}
#' tikz('tikz-boxplot.tex', width = 4.5, height = 3.0)
#' boxplot(iris$Sepal.Width ~ iris$Species,col=2:4,
#'         main="boxplot",pch="+",xlab="Species",
#'         ylab="Sepal.Width",axes=FALSE)
#' bkcd$axes()
#' #axis(1,lwd=0,lwd.ticks=1,labels=levels(iris$Species),at=1:3)
#' dev.off()
#' bkcd$tikz2xkcd("tikz-boxplot.tex","tikz-boxplot.png",fontname="Fuzzy Bubbles")
#' ```
#' 
#' <div class="center">
#' ![](tikz-boxplot.png)
#'
#' **Figure 6**: boxplot demo.
#' </div>
#'
#' Now a flowchart which illustrates as well the concept of chessboard coordinate based layouts:
#' 
#' ```{r label=flowchart,results="hide",cache=TRUE}
#' library(diagram)
#' library(png)
#' # https://svgsilh.com/search/stickman-1.html
#' pp <- readPNG("stickman.png")
#' tikz('tikz-flowchart.tex', width = 4.5, height = 4.5)
#' par(cex=0.8,mai=rep(0.3,4))
#' # setup elements using chessboard coordinates
#' board = function (x,y=NULL,func=NULL,...) {
#'     f2v = function (x) {
#'         col=substr(x,1,1)
#'         col=as.integer(which(LETTERS==col))
#'         row=as.integer(substr(x,2,2))
#'         return(c(col,row))
#'     }
#'     from = f2v(x)
#'     if (class(y)=="function") {
#'         invisible(y(from,...))
#'         
#'     } else {
#'         to   = f2v(y) 
#'         invisible(func(from,to,...))
#'     }
#' }
#' # helper function to set defaults
#' trect = function (pos,box.col="#47B8B8",
#'                   radx=0.65,rady=0.5,
#'                   shadow.size = 0.1,shadow.col = "#99999966",...) {
#'    textrect(pos,box.col=box.col,radx=radx,rady=rady,
#'             shadow.size=shadow.size,
#'             shadow.col=shadow.col,...)
#' }
#' 
#' # the surface
#' bkcd$emptyplot(xlim=c(0.2,6.5),ylim=c(0.2,6.5))
#' # display the coordinate system - just for illustration
#' grid(lwd=2,lty=2)
#' axis(1,at=c(1:6),labels=LETTERS[1:6],lwd=0)
#' axis(2,at=c(1:6),labels=1:6,lwd=0)
#' box()
#' 
#' # first the lines
#' board('A6','A4',straightarrow)
#' board('A4','A2',straightarrow)
#' board('A2','C2',straightarrow)
#' board('C2','E3',straightarrow)
#' board('C2','E1',straightarrow)
#' 
#' # then the rectangles
#' board('A6',trect,lab="R-code")
#' board('A4',trect,lab="tikzDevice\nTex")         
#' board('A2',trect,lab="bkcd.R\nTex")
#' board('C2',trect,lab="xelatex\nPdf")
#' board('E3',trect,radx=0.75,lab="Ghostscript\nPng")
#' board('E1',trect,radx=0.75,lab="pdf2svg\nSvg")
#' board('D5',trect,radx=1.0,lab="Chunk\nProcessing",box.col="#D89999") 
#' # finished ??
#' rasterImage(pp,2.5,2.8,3.8,4.2)
#' dev.off()
#' # conversion
#' bkcd$tikz2xkcd("tikz-flowchart.tex","tikz-flowchart.png",fontname="Fuzzy Bubbles")
#' # just a pdf
#' bkcd$tikz2xkcd("tikz-flowchart.tex","tikz-flowchart.pdf",fontname="Fuzzy Bubbles")
#' ```
#'
#' <div class="center">
#' <a name="flowchart"> </a>
#' ![](tikz-flowchart.png)
#'
#' **Figure 7**: flowchart demo.
#' </div>

#' 
#' Please note, the `emptyplot` function keeps the aspect ratio, this is here required as it avoids resizing the board differentially in the X and Y dimension.
#'
#' 
#' ## CITATION
#' <a name="citation"> </a>
#' 
#' How to cite this script:
#' 
# TODO: Github URL

#' ```
#' # notrun
#' @Misc{Groth2022bkcd,
#'   author =   {Detlef Groth},
#'   title =    {bkcd.{R} - {R} functions to create XKCD like plots and figures using base graphics.},
#'   howpublished = {\url{https://github.com/mittelmark/Rcode},
#'   year = {2022}
#' }
#' ```
#' 
#' Groth, D. (2022). bkcd.R -  R functions to create XKCD like plots and figures using base graphics. [https://github.com/mittelmark/Rcode](https://github.com/mittelmark/Rcode)
#' 
#' ## DOCUMENTATION
#' <a name="documentation"> </a>
#' 
#' This documentation was created directly from the file *bkcd.R* using the following commands in the terminal:
#' 
#' ```
#' # notrun
#' Rscript bkcd.R --docu
#' ```
#' 
#' The script `bkcd.R` can be executed directly from the command line as described above, using the docu flag all lines starting with 
#' the `#'` character sequence are extracted and then processed using the library [rmarkdown](https://cran.r-project.org/web/packages/rmarkdown) which evaluates the embedded code chunks.
#' 
#' ## LINKS
#' <a name="links"> </a>
#' 
#' * useful fonts:
#'     * [xkcd Script](https://github.com/ipython/xkcd-font/tree/master/xkcd-script/font)
#'     * [Humor Sans](https://github.com/shreyankg/xkcd-desktop)
#'     * [Fuzzy Bubbles](https://fonts.google.com/specimen/Fuzzy+Bubbles)
#' 
#' Here a comparison of the three fonts:
#' 
#' ```{r label=boxplot2,results="hide",cache=TRUE}
#' bkcd$tikz2xkcd("tikz-boxplot.tex","tikz-boxplot-humor.png",fontname="Humor Sans")
#' bkcd$tikz2xkcd("tikz-boxplot.tex","tikz-boxplot-xkcd.png",fontname="xkcd Script")
#' ```
#' 
#' | Fuzzy Bubbles            |  Humor Sans            | xkcd Script |
#' | :---------------------:  | :-------------------:  | :--------:  |
#' | ![Fuzzy Bubbles](tikz-boxplot.png){#id width=300px} | ![Humor Sans](tikz-boxplot-humor.png){#id width=300px} | ![xkcd Script](tikz-boxplot-xkcd.png){#id width=300px} |
#' 
#' <div class="center">
#' **Table 1**: Fonts demo.
#' </div>
#'
#' ## TODO's
#' <a name="todos"> </a>
#' 
#' * embedding svg conversion using pdf2svg
#' * deleting temporary LaTeX files, they are currently left for inspection
#' * checking [svg2tikz](https://github.com/xyz2tex/svg2tikz)  for using Cairo-Svg instead of [tikzDevice](https://cran.r-project.org/web/packages/tikzDevice/)  for output
#' * caching of subsequent runs of tikz2xkcd, first pdf, then png to avoid code re-execution if not neccessary
#' 
#' ## CHANGELOG
#' <a name="changelog"> </a>
#' 
#' * 2022-01-30 (Version 0.1) - initial release
#' 
#' ## DISCLAIMER
#' 
#' There is no warranty of any kind! Use at your own risk!!
#' 
#' These R functions should be used using the basic
#' graphics engine. Users of ggplot2 should use the xkcd package from CRAN, see here: [https://cran.r-project.org/package=xkcd](https://cran.r-project.org/package=xkcd), the lattice library seems not to work with the tikzDevice package.
#' 
#' ## LICENSE (MIT)
#' <a name="license"> </a>
#' 
#' Copyright 2022 Detlef Groth, Scwielowsee, Germany
#' 

#' Permission is hereby granted, free of charge, to any person obtaining a
#' copy of this software and associated documentation files (the "Software"),
#' to deal in the Software without restriction, including without limitation
#' the rights to use, copy, modify, merge, publish, distribute, sublicense,
#' and/or sell copies of the Software, and to permit persons to whom the
#' Software is furnished to do so, subject to the following conditions: 
#'
#' The above copyright notice and this permission notice shall be included in
#' all copies or substantial portions of the Software. 
#'
#' THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#' IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#' FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#' AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#' LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
#' FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
#' DEALINGS IN THE SOFTWARE. 
#' 

if (sys.nframe() == 0L && !interactive()) {
    # if running via Rscript
    argv=commandArgs()
    idx=grep("--file",argv)
    bkcd$FILENAME=gsub("--file=","",argv[idx])
    if (any(grepl("--docu",argv))) {
        t1=Sys.time()
        cat(" running", bkcd$FILENAME,"\n")
        
        fin  = file(bkcd$FILENAME, "r")
        
        outfile=gsub("\\.R",".Rmd",bkcd$FILENAME)
        fout = file(outfile,'w')
        
        while(length((line = readLines(fin,n=1)))>0) {
            if (grepl("^\\s*#'",line)) {
                line=gsub("^\\s*#' ?","",line)       
                cat(line,"\n",file=fout)
            }
        }
        close(fin)
        close(fout)
        #knitr::knit(outfile)
        library(rmarkdown)
        render(outfile,html_document(css="mini.css",theme=NULL))
        cat("Processing done in",round(as.numeric(Sys.time()-t1,units="secs"),2),"seconds!\n")
    } else if (any(grepl("--convert",argv))) {
        idx=grep("--convert",argv)
        if (length(argv) != idx+2) {
            cat("Error: Wrong number of arguments!\n")
            cat("     Usage: bkcd.R --convert infile.tex outfile.png|tex|png\n")
            q()
        }
        idx=grep("--convert",argv)
        infile=argv[idx+1]
        if (!file.exists(infile)) {
            cat("Error: File '",infile,"' does not exists!\n")
            q()
        }
        outfile=argv[idx+2]
        cat("processing",infile,"...")
        bkcd$tikz2xkcd(infile,outfile,standalone=TRUE)
        cat(". done!\n")
    } else if (any(grepl("--help",argv))) {
        idx=grep("--help",argv)
        if (length(argv) == idx) {
            bkcd$Usage()
        } 
        funcname=argv[idx+1]
        # show public methods
        pubmeths=ls(bkcd,pattern="^[a-z]")
        if (any(grepl(funcname,pubmeths))) {
            fin  = file(bkcd$FILENAME, "r")
            flag=FALSE
            while(length((line = readLines(fin,n=1)))>0) {
                if (grepl(paste("^\\s*#' +\\*\\*bkcd.",funcname,sep=""),line)) {
                    flag=TRUE
                }
                if (flag & !(grepl("^\\s*#'",line))) {
                    break
                }
                if (flag) {
                    cat(gsub("^> ```","```",gsub("^\\s*#' ?","",line)),"\n")
                }             
            }
            close(fin)
        } else {
            cat("Error: Wrong method! Valid ones are: ",paste(pubmeths,collapse=", "),"\n")
        }
    } else if (any(grepl("--test",argv))) {
        tikz("file-test.tex",sanitize=TRUE)
        barplot(1:4,names.arg=LETTERS[1:4],col=2:5,axes=FALSE,
                main="barplot",ylim=c(0,4.5))
        bkcd$axes(2)
        dev.off()
        t1=Sys.time()
        cat("Creating file-test.pdf ...")
        bkcd$tikz2xkcd("file-test.tex","file-test.pdf",fontname="Humor Sans")
        cat(". done!\n Creating file-test.png ...")
        bkcd$tikz2xkcd("file-test.tex","file-test.png",fontname="Humor Sans")
        cat(". done!\n")
        cat("Processing done in",round(as.numeric(Sys.time()-t1,units="secs"),2),"seconds!\n")
    } else {
        bkcd$Usage()
    }
}

